config/routes.rb
MediaLibrary::Application.routes.draw do
  resources :genres

  resources :countries

end

app/models/country.rb
class Country < Neo4j::Rails::Model
  property :name, :type => String
  property :code, :type => String, :index => :exact, :unique => true

  validates :code, :presence => true, :uniqueness => true
end

app/models/episode.rb
class Episode < Neo4j::Rails::Model
  property :title, :type => String
  property :num_in_season, :type => Fixnum
  property :production_id, :type => String
  property :air_date, :type => Date
  property :tvrage_episode_link, :type => String

end

app/models/genre.rb
class Genre < Neo4j::Rails::Model
  property :name, :type => String, :index => :exact, :unique => true

  validates :name, :presence => true, :uniqueness => :true
end

app/models/movie.rb
class Movie < Neo4j::Rails::Model
  property :title, :year, :index => :exact
  property :tmdb_id, :index => :exact, :unique => true
  property :tmdb_url, :index => :exact, :unique => true
  property :imdb_url, :index => :exact, :unique => true
  property :imdb_id, :index => :exact, :unique => true
  property :overview
  property :released, :type => Date
  property :updated_at, :type => Date
  property :created_at, :type => Date
  has_n(:countries).to(Country)
  has_n(:people).from(Person, :acted_in)
  has_one(:sequel)
  has_n(:posters).to(Poster)
  validates :title, :presence => :true
  validates :tmdb_id, :uniqueness => true
  validates :imdb_id, :uniqueness => true

end

app/models/person.rb
class Person < Neo4j::Rails::Model
  property :name, :type => String
  property :birth_date, :type => String
  property :tmdb_id, :type => String, :index => :exact, :unique => true
  property :biography, :type => String
  has_n(:acted_in).to(Movie).relationship(Role)
  has_n(:appeared_in).to(Episode).relationship(Role)
end

app/models/season.rb
class Season < Neo4j::Rails::Relationship
  property :number
end

app/models/show.rb
class Show < Neo4j::Rails::Model
  property :name, :type => String
  property :rageid, :type => String, :index => :exact, :unique => true
  property :started, :type => Fixnum
  property :run_time, :type => Fixnum
  property :start_date, :type => Date
  property :status, :type => String
  property :ended, :type => Date
  has_n(:episodes).to(Episode).relationship(Season)
  has_n(:countries)
  has_n(:genres)
  validates :name, :presence => true
  validates :rageid, :presence => true, :uniqueness => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  # GET /countries
  # GET /countries.json
  def index
    @countries = Country.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @countries }
    end
  end

  # GET /countries/1
  # GET /countries/1.json
  def show
    @country = Country.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @country }
    end
  end

  # GET /countries/new
  # GET /countries/new.json
  def new
    @country = Country.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @country }
    end
  end

  # GET /countries/1/edit
  def edit
    @country = Country.find(params[:id])
  end

  # POST /countries
  # POST /countries.json
  def create
    @country = Country.new(params[:country])

    respond_to do |format|
      if @country.save
        format.html { redirect_to @country, notice: 'Country was successfully created.' }
        format.json { render json: @country, status: :created, location: @country }
      else
        format.html { render action: "new" }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /countries/1
  # PUT /countries/1.json
  def update
    @country = Country.find(params[:id])

    respond_to do |format|
      if @country.update_attributes(params[:country])
        format.html { redirect_to @country, notice: 'Country was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /countries/1
  # DELETE /countries/1.json
  def destroy
    @country = Country.find(params[:id])
    @country.destroy

    respond_to do |format|
      format.html { redirect_to countries_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  # GET /genres
  # GET /genres.json
  def index
    @genres = Genre.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @genres }
    end
  end

  # GET /genres/1
  # GET /genres/1.json
  def show
    @genre = Genre.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @genre }
    end
  end

  # GET /genres/new
  # GET /genres/new.json
  def new
    @genre = Genre.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @genre }
    end
  end

  # GET /genres/1/edit
  def edit
    @genre = Genre.find(params[:id])
  end

  # POST /genres
  # POST /genres.json
  def create
    @genre = Genre.new(params[:genre])

    respond_to do |format|
      if @genre.save
        format.html { redirect_to @genre, notice: 'Genre was successfully created.' }
        format.json { render json: @genre, status: :created, location: @genre }
      else
        format.html { render action: "new" }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /genres/1
  # PUT /genres/1.json
  def update
    @genre = Genre.find(params[:id])

    respond_to do |format|
      if @genre.update_attributes(params[:genre])
        format.html { redirect_to @genre, notice: 'Genre was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /genres/1
  # DELETE /genres/1.json
  def destroy
    @genre = Genre.find(params[:id])
    @genre.destroy

    respond_to do |format|
      format.html { redirect_to genres_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/countries/_form.html.haml
= form_for @country do |f|
  - if @country.errors.any?
    #error_explanation
      %h2= "#{pluralize(@country.errors.count, "error")} prohibited this country from being saved:"
      %ul
        - @country.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :code
    = f.text_field :code
  .actions
    = f.submit 'Save'

app/views/countries/edit.html.haml
%h1 Editing country

= render 'form'

= link_to 'Show', @country
\|
= link_to 'Back', countries_path

app/views/countries/index.html.haml
%h1 Listing countries

%table
  %tr
    %th Name
    %th Code
    %th
    %th
    %th

  - @countries.each do |country|
    %tr
      %td= country.name
      %td= country.code
      %td= link_to 'Show', country
      %td= link_to 'Edit', edit_country_path(country)
      %td= link_to 'Destroy', country, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Country', new_country_path

app/views/countries/new.html.haml
%h1 New country

= render 'form'

= link_to 'Back', countries_path

app/views/countries/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @country.name
%p
  %b Code:
  = @country.code

= link_to 'Edit', edit_country_path(@country)
\|
= link_to 'Back', countries_path

app/views/genres/_form.html.haml
= form_for @genre do |f|
  - if @genre.errors.any?
    #error_explanation
      %h2= "#{pluralize(@genre.errors.count, "error")} prohibited this genre from being saved:"
      %ul
        - @genre.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/genres/edit.html.haml
%h1 Editing genre

= render 'form'

= link_to 'Show', @genre
\|
= link_to 'Back', genres_path

app/views/genres/index.html.haml
%h1 Listing genres

%table
  %tr
    %th Name
    %th
    %th
    %th

  - @genres.each do |genre|
    %tr
      %td= genre.name
      %td= link_to 'Show', genre
      %td= link_to 'Edit', edit_genre_path(genre)
      %td= link_to 'Destroy', genre, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Genre', new_genre_path

app/views/genres/new.html.haml
%h1 New genre

= render 'form'

= link_to 'Back', genres_path

app/views/genres/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @genre.name

= link_to 'Edit', edit_genre_path(@genre)
\|
= link_to 'Back', genres_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Media Library
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    = yield